{% set name = "python-yakh" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_yakh-{{ version }}.tar.gz
  sha256: da03e800b4f2f5d85344f1668e852687c12dc1a99a03c65cf3dc13a3680da49d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - yakh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/petereon/yakh
  summary: Yet Another Keypress Handler
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
